flags: {}
packages:
- '.'
- '../gl-pal'
- '../glfw-pal'
- '../vr-pal'
- '../hydra-hs'
- '../halive'
- '../linear-extra'
- '../lens-extra'
- '../openvr-hs'
- '../bindings-GLFW-3.1.1.4'
resolver: nightly-2015-11-03
